src/Entity/Animal.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AnimalRepository")
 */
class Animal
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=50)
     */
    private $nome;

    /**
     * @var date
     *
     * @ORM\Column(type="date")
     */
    private $data_nascimento;

    /**
     * @var object
     *
     * @ORM\ManyToMany(targetEntity="App\Entity\Cliente", mappedBy="animal")
     *
     */
    private $cliente;

    /**
     * @var object
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Raca", inversedBy="id")
     */
    private $raca;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getNome()
    {
        return $this->nome;
    }

    /**
     * @param string $nome
     * @return Animal
     */
    public function setNome($nome)
    {
        $this->nome = $nome;
        return $this;
    }

    /**
     * @return date
     */
    public function getDataNascimento()
    {
        return $this->data_nascimento;
    }

    /**
     * @param date $data_nascimento
     * @return Animal
     */
    public function setDataNascimento($data_nascimento)
    {
        $this->data_nascimento = $data_nascimento;
        return $this;
    }

    /**
     * @return object
     */
    public function getCliente()
    {
        return $this->cliente;
    }

    /**
     * @param object $cliente
     * @return Animal
     */
    public function setCliente($cliente)
    {
        $this->cliente = $cliente;
        return $this;
    }

    /**
     * @return object
     */
    public function getRaca()
    {
        return $this->raca;
    }

    /**
     * @param object $raca
     * @return Animal
     */
    public function setRaca($raca)
    {
        $this->raca = $raca;
        return $this;
    }



}

src/Controller/AnimaisController.php
<?php

namespace App\Controller;

use App\Entity\Animal;
use App\Form\AnimalType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class AnimaisController extends Controller
{
    /**
     * @Route("/animais", name="listar_animais")
     * @Template("animais/index.html.twig")
     */
    public function index()
    {
        $em = $this->getDoctrine()->getManager();

        $animais = $em->getRepository(Animal::class)->findAll();

        return [
            'animais' => $animais
        ];
    }

    /**
     * @Route("/animais/visualizar/{id}", name="visualizar_animal")
     * @Template("animais/view.html.twig")
     * @param Animal $animal
     * @return array
     */
    public function view(Animal $animal)
    {
        return [
            'animal' => $animal
        ];
    }

    /**
     * @Route("animal/cadastrar", name="cadastrar_animal")
     * @Template("animais/create.html.twig")
     */
    public function create(Request $request)
    {
        $animal = new Animal();
        $form = $this->createForm(AnimalType::class, $animal);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($animal);
            $em->flush();

            $this->addFlash('success', "Animal foi salvo com sucesso!");
            return $this->redirectToRoute('listar_animais');
        }

        return [
            'form' => $form->createView()
        ];
    }
}

templates/animais/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cadastrar Animal - {% endblock %}

{% block body %}
    <h1>Cadastrar Animal</h1>
    <hr>
    {{ form(form) }}
{% endblock %}

templates/animais/index.html.twig
{% extends "base.html.twig" %}

{% block title %} Listagem de Animais - {% endblock %}

{% block body %}

    {% for flashMessage in app.session.flashbag.get('success') %}
        <div class="alert alert-success">
            {{ flashMessage }}
        </div>
    {% endfor %}
    {% for flashMessage in app.session.flashbag.get('warning') %}
        <div class="alert alert-warning">
            {{ flashMessage }}
        </div>
    {% endfor %}
    {% for flashMessage in app.session.flashbag.get('danger') %}
        <div class="alert alert-danger">
            {{ flashMessage }}
        </div>
    {% endfor %}
    <h1>Listagem de Animais</h1>
    <hr>
    <div class="row">
        <div class="col-md-12">
            <a href="{{ path('cadastrar_animal') }}" class="btn btn-primary">Cadastrar Animal</a>
        </div>
    </div>
    <table class="table table-hover table-striped mt-3">
        <thead>
        <tr>
            <th>Cod.</th>
            <th>Nome</th>
            <th>Data Nasc.</th>
        </tr>
        </thead>
        <tbody>
        {% for animal in animais %}
            <tr>
                <td>{{ animal.id }}</td>
                <td><a href="{{ path('visualizar_animal', {'id': animal.id}) }}">{{ animal.nome }}</a></td>
                <td>{{ animal.dataNascimento|date("d/m/Y") }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">Nenhum registro encontrado!</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}

templates/animais/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ animal.nome }} - Visualizar Animal - {% endblock %}

{% block body %}

    <h1>Visualizando Animal - {{ animal.nome }}</h1>
    <table class="table table-striped">
        <tr>
            <th colspan="2">Dados do animal</th>
        </tr>
        <tr>
            <th>Cod.</th>
            <td>{{ animal.id }}</td>
        </tr>
        <tr>
            <th>Nome</th>
            <td>{{ animal.nome }}</td>
        </tr>
        <tr>
            <th>Data de Nasc.</th>
            <td>{{ animal.dataNascimento|date("d/m/Y") }}</td>
        </tr>
        <tr>
            <th colspan="2">Proprietários</th>
        </tr>
        <tr>
            <th></th>
            <td>
                <ul>
                    {% for cliente in animal.cliente %}
                        <li><a href="{{ path('visualizar_cliente', {'id': cliente.id}) }}">{{ cliente.nome }}</a></li>
                    {% else %}
                        <li>
                            Esse animal não tem nenhum proprietário. <br>
                            Quer adota-lo?
                        </li>
                    {% endfor %}
                </ul>
            </td>
        </tr>

    </table>

{% endblock %}